# @package _global_
dataset:
  coeff: 4.0
  cf_seq_mode: random_trajectories

model:
  name: CT_alpha0_rt
  multi:
    optimizer:
      learning_rate: 0.01
    batch_size: 256
    seq_hidden_units: 16
    br_size: 16
    fc_hidden_units: 32
    dropout_rate: 0.1

  self_positional_encoding:
    max_relative_position: 15

exp:
  weights_ema: True
  alpha: 0.0
  update_alpha: False
  beta: 0.99
  balancing: domain_confusion
  max_epochs: 150